### ISSUE TITLE
Project maintenance

### ISSUE THREAD

**Issue by azzamsa** [TahaSh/svelte-paginate#30]
Hi @TahaSh.

I think we have some pending pull request untouched for years. 
My suggestions is that allowing one of us to have access to merge this PR.

Thanks for svelte-paginate.

**Comment by TahaSh** [comment]
Sorry @azzamsa for taking too long to handle the PRs. All are merged now and it should be working in sveltekit. I'm back on this project, so you should see more updates in the future.
