### ISSUE TITLE
Uncaught TypeError: items is undefined

### ISSUE THREAD

**Issue by norricorp** [TahaSh/svelte-paginate#33]
In the example code, the list of objects is in "items", which is used in paginatedItems. To fit this into an existing app that uses "articles", I have the following (I have left out a lot of the code)

let hero, articles;
...
  async function fetchData() {
....
    const [first, ...rest] = formattedArticles;
    hero = first;
    articles = rest;
  }
  onMount(fetchData);
  $: paginatedItems = paginate({ articles, pageSize, currentPage })
.....
      {#if articles}
        <div class="articles-grid">
          {#each paginatedItems  as article, index}
            <Article {article} bordered={index !== articles.length - 1} />
          {/each}
        </div>
      {/if}

When I run this in the browser, I get an error of 
Uncaught TypeError: items is undefined
    paginate paginate.js:2

Is this expecting the data to be in "items". I have essentially replaced "items" in the example with "articles"

Regards,

**Comment by TahaSh** [comment]
@norricorp the `paginate` function expects to get an object with these three keys: `items`, `pageSize`, and `currentPage`. In your case, you're not specifying `items` in the object. So, to fix it, update `paginatedItems` to this:
```js
$: paginatedItems = paginate({ items: articles, pageSize, currentPage })
```

**Comment by norricorp** [comment]
Hi @TahaSh, thanks for getting back so quickly
So I changed paginatedItems to 

let items;
const [first, ...rest] = formattedArticles;
    hero = first;
    articles = rest;
  }

  onMount(fetchData);
  $: paginatedItems = paginate({ items: articles, pageSize, currentPage })
  
  In the browser console, I get
  Uncaught TypeError: items is undefined
    paginate paginate.js:2
    update Home.svelte:39
    
line 39 in home.svelte is where paginatedItems is defined.

So then I changed "articles" to "items"

    const [first, ...rest] = formattedArticles;
    hero = first;
    items = rest;
  }

  onMount(fetchData);
  $: paginatedItems = paginate({ items, pageSize, currentPage })

</script>

<main>
  <section class="main-content">
    <div class="container">
      {#if hero}
        <Hero article={hero} />
      {/if}
      {#if items}
        <div class="articles-grid">
          {#each paginatedItems  as article, index}
            <Article {article} bordered={index !== items.length - 1} />
          {/each}
        </div>
      {/if}

And, once again, in console

Uncaught (in promise) TypeError: items is undefined
    paginate paginate.js:2
    update Home.svelte:39
    

Any other ideas? Obviously I am doing something very wrong.

**Comment by TahaSh** [comment]
@norricorp it's actually hard for me to tell without seeing the full code. But I think it's related to the code fetching the data. Also, please make sure you're using the latest version `v0.1.0`.

Feel free to send me a gist (or whatever you like) of the homepage full code and I'll take a look.

**Comment by norricorp** [comment]
https://gist.github.com/norricorp/011edb9f70280772f215797ee9203416

**Comment by TahaSh** [comment]
@norricorp it's erroring because `articles` is `undefined` initially, but `paginate` is expecting an array. So you can fix it by checking if `articles` is valid before calling `paginate`:

```js
$: paginatedItems = articles && paginate({ items: articles, pageSize, currentPage })
```

Also, don't forget to add this check for `<PaginationNav />`:

```html
{#if articles}
  <PaginationNav
    totalItems="{articles.length}"
    pageSize="{pageSize}"
    currentPage="{currentPage}"
    limit="{1}"
    showStepOptions="{true}"
    on:setPage="{(e) => currentPage = e.detail.page}"
  /> 
{/if}
```

Please let me know if you have any other questions :).

**Comment by norricorp** [comment]
Hi @TahaSh ,
that worked. Thank you so much for great support.
Are you intending to get this to version 1.0? What extra functionality do you plan? (I realise nothing to do with my issue - just interested)

**Comment by TahaSh** [comment]
Hi @norricorp, I'm really glad that it worked.

I have no plans for this package at the moment, but if you have anything in your mind for this package or even a new package, I would be more than happy to put it on my list. Thanks!
